// <auto-generated />
using System;
using FlowCiao.Persistence.Providers.Rdbms;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowCiao.Persistence.Providers.Rdbms.SqlServer.Migrations
{
    [DbContext(typeof(FlowCiaoDbContext))]
    partial class FlowCiaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("FlowCiao")
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FlowCiao.Models.Core.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<byte[]>("ActorContent")
                        .HasMaxLength(1000000)
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorName")
                        .IsUnique()
                        .HasFilter("[ActorName] IS NOT NULL");

                    b.ToTable("Activity", "FlowCiao");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.Flow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flow", "FlowCiao");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.ToTable("State", "FlowCiao");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.StateActivity", b =>
                {
                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StateId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("StateActivity", "FlowCiao");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.Transition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FromStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ToStateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("FromStateId");

                    b.HasIndex("ToStateId");

                    b.ToTable("Transition", "FlowCiao");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.TransitionActivity", b =>
                {
                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransitionId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.ToTable("TransitionActivity", "FlowCiao");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.TransitionTrigger", b =>
                {
                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TriggerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransitionId", "TriggerId");

                    b.HasIndex("TriggerId");

                    b.ToTable("TransitionTrigger", "FlowCiao");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.ToTable("Trigger", "FlowCiao");
                });

            modelBuilder.Entity("FlowCiao.Models.Execution.FlowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecutionState")
                        .HasColumnType("int");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Progress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.ToTable("FlowExecution", "FlowCiao");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.State", b =>
                {
                    b.HasOne("FlowCiao.Models.Core.Flow", "Flow")
                        .WithMany("States")
                        .HasForeignKey("FlowId");

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.StateActivity", b =>
                {
                    b.HasOne("FlowCiao.Models.Core.Activity", "Activity")
                        .WithMany("StateActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowCiao.Models.Core.State", "State")
                        .WithMany("StateActivities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("State");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.Transition", b =>
                {
                    b.HasOne("FlowCiao.Models.Core.Flow", "Flow")
                        .WithMany("Transitions")
                        .HasForeignKey("FlowId");

                    b.HasOne("FlowCiao.Models.Core.State", "From")
                        .WithMany()
                        .HasForeignKey("FromStateId");

                    b.HasOne("FlowCiao.Models.Core.State", "To")
                        .WithMany()
                        .HasForeignKey("ToStateId");

                    b.Navigation("Flow");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.TransitionActivity", b =>
                {
                    b.HasOne("FlowCiao.Models.Core.Activity", "Activity")
                        .WithMany("TransitionActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowCiao.Models.Core.Transition", "Transition")
                        .WithMany("TransitionActivities")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Transition");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.TransitionTrigger", b =>
                {
                    b.HasOne("FlowCiao.Models.Core.Transition", "Transition")
                        .WithMany("TransitionTriggers")
                        .HasForeignKey("TransitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowCiao.Models.Core.Trigger", "Trigger")
                        .WithMany("TransitionTriggers")
                        .HasForeignKey("TriggerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Transition");

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.Trigger", b =>
                {
                    b.HasOne("FlowCiao.Models.Core.Flow", "Flow")
                        .WithMany()
                        .HasForeignKey("FlowId");

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("FlowCiao.Models.Execution.FlowExecution", b =>
                {
                    b.HasOne("FlowCiao.Models.Core.Flow", "Flow")
                        .WithMany()
                        .HasForeignKey("FlowId");

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.Activity", b =>
                {
                    b.Navigation("StateActivities");

                    b.Navigation("TransitionActivities");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.Flow", b =>
                {
                    b.Navigation("States");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.State", b =>
                {
                    b.Navigation("StateActivities");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.Transition", b =>
                {
                    b.Navigation("TransitionActivities");

                    b.Navigation("TransitionTriggers");
                });

            modelBuilder.Entity("FlowCiao.Models.Core.Trigger", b =>
                {
                    b.Navigation("TransitionTriggers");
                });
#pragma warning restore 612, 618
        }
    }
}
